version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_SERVICE_API_KEY=${EMAIL_SERVICE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    # volumes:
    #   - .:/app
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
